action_list: ['Cap Off', 'Apply Tip', 'Setting Units', 'Priming', 'Injection', 'Remove Tip', 'Cap On']
executionOptions:
  action_analysis: true
  entropy_stats: false
  general_analysis: true
  hitradius: 20
  kcoeff_analysis: true
  novice_results: true
  ooi_analysis: true
  sequence_comparison: false
paths:
  input: C:/Users/renee/OneDrive/Dokumente/ETHZ/Master_Thesis/05_Framework/Framework/data/input/
  output: C:/Users/renee/OneDrive/Dokumente/ETHZ/Master_Thesis/05_Framework/Framework/data/output/
template_sequence: ['Cap Off', 'Apply Tip', 'Setting Units', 'Priming', 'Setting Units', 'Injection', 'Setting Units', 'Remove Tip', 'Cap On']
