action_list: []
executionOptions:
  action_analysis: false
  entropy_stats: true
  general_analysis: true
  hitradius: 20
  kcoeff_analysis: true
  novice_results: true
  ooi_analysis: true
  sequence_comparison: false
paths:
  input: data/input/example_input/
  output: data/output/example_output/
template_sequence: []