action_list: ['Cap Off', 'Apply Tip', 'Setting Units', 'Priming', 'Injection', 'Remove Tip', 'Cap On']
executionOptions:
  action_analysis: true
  entropy_stats: true
  general_analysis: false
  hitradius: 23
  kcoeff_analysis: true
  novice_results: false
  ooi_analysis: true
  sequence_comparison: false
paths:
  input: C:/Users/renee/OneDrive/Dokumente/ETHZ/Master_Thesis/05_Framework/Framework/data/input/gaze_input_tobii_ogd_kcoeff
  output: C:/Users/renee/OneDrive/Dokumente/ETHZ/Master_Thesis/05_Framework/Framework/data/output/last_test
template_sequence: ['Cap Off', 'Apply Tip', 'Setting Units', 'Priming', 'Injection', 'Remove Tip', 'Cap On']
