action_list: []
executionOptions:
  action_analysis: false
  entropy_stats: true
  general_analysis: true
  hitradius: 20
  kcoeff_analysis: true
  novice_results: true
  ooi_analysis: true
  sequence_comparison: false
paths:
  input: C:/Users/renee/OneDrive/Dokumente/ETHZ/Master_Thesis/05_Framework/Framework/data/input/example_input/
  output: C:/Users/renee/OneDrive/Dokumente/ETHZ/Master_Thesis/05_Framework/Framework/data/output/example_output/
template_sequence: []
