action_list: null
executionOptions:
  action_analysis: false
  entropy_stats: false
  general_analysis: true
  hitradius: 2
  kcoeff_analysis: false
  novice_results: true
  ooi_analysis: false
  sequence_comparison: false
paths:
  input: C:/Users/renee/OneDrive/Dokumente/ETHZ/Master_Thesis/05_Framework/Framework/Data_old/test_input_gui
  output: C:/Users/renee/OneDrive/Dokumente/ETHZ/Master_Thesis/05_Framework/Framework/Data_old/Output
template_sequence: null
