action_list:
- Action1
- Action2
- Action3
- Action4
executionOptions:
  action_analysis: true
  entropy_stats: false
  general_analysis: true
  hitradius: 20
  kcoeff_analysis: true
  novice_results: true
  ooi_analysis: true
  sequence_comparison: true
paths:
  input: C:/Users/renee/OneDrive/Dokumente/ETHZ/Master_Thesis/05_Framework/Framework/data/input
  output: C:/Users/renee/OneDrive/Dokumente/ETHZ/Master_Thesis/05_Framework/Framework/data/output
template_sequence:
- Action2
- Action3
- Action1
- Action2
