action_list:
- '''Cap Off'''
- '''Apply Tip'''
- '''Setting Units'''
- '''Priming'''
- '''Injection'''
- '''Remove Tip'''
- '''Cap On'''
executionOptions:
  action_analysis: true
  entropy_stats: true
  general_analysis: true
  hitradius: 20
  kcoeff_analysis: true
  novice_results: true
  ooi_analysis: true
  sequence_comparison: true
paths:
  input: C:/Users/renee/OneDrive/Dokumente/ETHZ/Master_Thesis/05_Framework/Framework/Data_old/gaze_input_tobii_ogd_kcoeff
  output: C:/Users/renee/OneDrive/Dokumente/ETHZ/Master_Thesis/05_Framework/Framework/Output
template_sequence:
- '''Cap Off'''
- '''Apply Tip'''
- '''Setting Units'''
- '''Priming'''
- '''Setting Units'''
- '''Injection'''
- '''Remove Tip'''
- '''Cap On'''
